[project]
name = "wp-test-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2.3",
    "pydantic>=2.10.5",
    "pydantic-settings>=2.7.1",
    "sqlalchemy>=2.0.37",
]
